repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
#      - id: check-added-large-files
      - id: name-tests-test
      - id: requirements-txt-fixer

## Black is the uncompromising Python code formatter
#  - repo: https://github.com/psf/black
#    rev: 23.9.1
#    hooks:
#      - id: black
#        args: [--line-length=200]

#  - repo: https://github.com/PyCQA/flake8
#    rev: 6.1.0
#    hooks:
#      - id: flake8
#        args: [--max-line-length=200]

## isort is a Python utility / library to sort imports alphabetically, and automatically separated into sections and by type
#  - repo: https://github.com/pycqa/isort
#    rev: v5.11.3
#    hooks:
#      - id: isort

## it checks for errors, enforces a coding standard
#  - repo: https://github.com/pycqa/pylint
#    rev: v3.0.1
#    hooks:
#      - id: pylint
#        args: [--max-line-length=200]
