USE hostelDB;
DROP TABLE IF EXISTS room_list;
CREATE TABLE IF NOT EXISTS room_list(
    ID BIGINT  UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    room_id INT UNSIGNED NOT NULL UNIQUE,
    room_name VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID)
);
