services:
  app:
    build: ./app
    depends_on:
      - db_test
    stdin_open: true
    tty: true

  db_test:
    image: mysql:8.0
    volumes:
      - db-test-data:/var/lib/mysql
      - ./app/src/tests/test_db/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"

volumes:
  db-test-data:
    driver: local
