version: '3.8'
services:
  pythonapp:
    build: ./app/
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    depends_on:
      - mysql

  mysql:
    build: ./db/
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8000:3306"

volumes:
  db-data:
    driver: local
