version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - MySQLUser=defaultUSER
        - MySQLPassword=defaultPWD
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=mysql://defaultUSER:defaultPWD@db:3306/hostelDB
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql  # Persist database data
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database schema
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"

volumes:
  db-data:  # Named volume for persisting database data
